run:
  timeout: 10s
  allow-parallel-runners: true

linters:
  enable-all: true
  disable:
    - depguard
    - execinquery
    - gomnd
    - exportloopref
    - exhaustruct
    - godox
    - intrange

linters-settings:
  gci:
    skip-generated: true
  varnamelen:
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-names:
      - err
      - tt

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - funlen