// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: protos/metrics/metrics.proto

package metrics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Instance       string  `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Group          string  `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Scenario       string  `protobuf:"bytes,3,opt,name=scenario,proto3" json:"scenario,omitempty"`
	Method         string  `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Url            string  `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Code           string  `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	Failed         bool    `protobuf:"varint,7,opt,name=failed,proto3" json:"failed,omitempty"`
	Timeout        bool    `protobuf:"varint,8,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Success        bool    `protobuf:"varint,9,opt,name=success,proto3" json:"success,omitempty"`
	LatencySeconds float64 `protobuf:"fixed64,10,opt,name=latencySeconds,proto3" json:"latencySeconds,omitempty"`
}

func (x *MetricV1) Reset() {
	*x = MetricV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_metrics_metrics_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricV1) ProtoMessage() {}

func (x *MetricV1) ProtoReflect() protoreflect.Message {
	mi := &file_protos_metrics_metrics_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricV1.ProtoReflect.Descriptor instead.
func (*MetricV1) Descriptor() ([]byte, []int) {
	return file_protos_metrics_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *MetricV1) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *MetricV1) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *MetricV1) GetScenario() string {
	if x != nil {
		return x.Scenario
	}
	return ""
}

func (x *MetricV1) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *MetricV1) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MetricV1) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MetricV1) GetFailed() bool {
	if x != nil {
		return x.Failed
	}
	return false
}

func (x *MetricV1) GetTimeout() bool {
	if x != nil {
		return x.Timeout
	}
	return false
}

func (x *MetricV1) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MetricV1) GetLatencySeconds() float64 {
	if x != nil {
		return x.LatencySeconds
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_metrics_metrics_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protos_metrics_metrics_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protos_metrics_metrics_proto_rawDescGZIP(), []int{1}
}

var File_protos_metrics_metrics_proto protoreflect.FileDescriptor

var file_protos_metrics_metrics_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x22, 0x8a, 0x02, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x56, 0x31, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72,
	0x69, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72,
	0x69, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65,
	0x6f, 0x75, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f,
	0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x26, 0x0a, 0x0e,
	0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x53, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x73, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0x3a, 0x0a,
	0x09, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x56, 0x31, 0x12, 0x2d, 0x0a, 0x04, 0x73, 0x65,
	0x6e, 0x64, 0x12, 0x11, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x4d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x56, 0x31, 0x1a, 0x0e, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x28, 0x01, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x61, 0x6d, 0x65, 0x61, 0x75, 0x78, 0x2f,
	0x62, 0x72, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_metrics_metrics_proto_rawDescOnce sync.Once
	file_protos_metrics_metrics_proto_rawDescData = file_protos_metrics_metrics_proto_rawDesc
)

func file_protos_metrics_metrics_proto_rawDescGZIP() []byte {
	file_protos_metrics_metrics_proto_rawDescOnce.Do(func() {
		file_protos_metrics_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_metrics_metrics_proto_rawDescData)
	})
	return file_protos_metrics_metrics_proto_rawDescData
}

var file_protos_metrics_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_metrics_metrics_proto_goTypes = []any{
	(*MetricV1)(nil), // 0: metrics.MetricV1
	(*Empty)(nil),    // 1: metrics.Empty
}
var file_protos_metrics_metrics_proto_depIdxs = []int32{
	0, // 0: metrics.MetricsV1.send:input_type -> metrics.MetricV1
	1, // 1: metrics.MetricsV1.send:output_type -> metrics.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_metrics_metrics_proto_init() }
func file_protos_metrics_metrics_proto_init() {
	if File_protos_metrics_metrics_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_metrics_metrics_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MetricV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_metrics_metrics_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_metrics_metrics_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_metrics_metrics_proto_goTypes,
		DependencyIndexes: file_protos_metrics_metrics_proto_depIdxs,
		MessageInfos:      file_protos_metrics_metrics_proto_msgTypes,
	}.Build()
	File_protos_metrics_metrics_proto = out.File
	file_protos_metrics_metrics_proto_rawDesc = nil
	file_protos_metrics_metrics_proto_goTypes = nil
	file_protos_metrics_metrics_proto_depIdxs = nil
}
